# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c

sudo: required

dist: trusty

before_install:
  - curl -OLs http://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget libboost-all-dev libboost-program-options-dev libboost-serialization-dev libarmadillo-dev r-cran-rcpp r-cran-rcpparmadillo 
  - ./run.sh install_dpkgcurl http://dirk.eddelbuettel.com/deb/trusty/libmlpack2_2.1.0-1.trusty.0_amd64.deb http://dirk.eddelbuettel.com/deb/trusty/libmlpack-dev_2.1.0-1.trusty.0_amd64.deb
  
script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
    