# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c

sudo: required

dist: trusty

before_install:
  - curl -OLs http://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  # add our launchpad repo which has (inter alia) the new mlpack 2.1.0
  - sudo add-apt-repository -y ppa:edd/misc
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget libmlpack-dev libboost-all-dev libboost-program-options-dev libboost-serialization-dev libarmadillo-dev r-cran-rcpp r-cran-rcpparmadillo 
  
script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
    